/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   exchange-search-list-item.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../paper-item/paper-item.d.ts" />
/// <reference path="../paper-item/paper-icon-item.d.ts" />
/// <reference path="../paper-item/paper-item-body.d.ts" />
/// <reference path="../star-rating/star-rating.d.ts" />
/// <reference path="exchange-search-item-mixin.d.ts" />

declare namespace UiElements {

  /**
   * `<exchange-search-list-item>` Displays a single list item for Exchange
   * search rersults panel.
   *
   * ### Example
   *
   * ```html
   * <exchange-search-list-item item="{...}" on-download="..."></exchange-search-list-item>
   * ```
   *
   * ### Styling
   *
   * `<exchange-search-list-item>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--exchange-search-list-item` | Mixin applied to the element | `{}`
   * `--exchange-search-list-item-action-button` | Mixin applied to the visible accrion button | `{}`
   * `--exchange-search-list-item-card-background-color` | Background color of the card item | `#fff`
   * `--rating-icon-color` | Color of the rating icons when highlighted | `--primary-text-color`
   * `--rating-unselected-opacity` | Color of the rating icons when not highlighted | `0.4`
   */
  class ExchangeSearchListItem extends
    ArcBehaviors.ExchangeSearchItemMixin(
    Polymer.Element) {
  }
}

interface HTMLElementTagNameMap {
  "exchange-search-list-item": UiElements.ExchangeSearchListItem;
}
