/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   exchange-search-grid-item.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {ExchangeSearchItemMixin} from './exchange-search-item-mixin.js';

declare namespace UiElements {

  /**
   * `<exchange-search-grid-item>` Displays a single grid item for Exchange
   * search rersults panel.
   *
   * ### Example
   *
   * ```html
   * <exchange-search-grid-item item="{...}" on-download="..."></exchange-search-grid-item>
   * ```
   *
   * ### Styling
   *
   * `<exchange-search-grid-item>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--exchange-search-grid-item` | Mixin applied to the element | `{}`
   * `--exchange-search-grid-item-action-button` | Mixin applied to the visible accrion button | `{}`
   * `--exchange-search-grid-item-card-background-color` | Background color of the card item | `#fff`
   * `--paper-rating-active-color` | Color of the rating icons when highlighted | `--accent-color`
   * `--paper-rating-inactive-color` | Color of the rating icons when not highlighted | `--disabled-text-color`
   * `--exchange-search-grid-item-tags-line` | Mixin applied to the tags container | `{}`
   */
  class ExchangeSearchGridItem extends
    ExchangeSearchItemMixin(
    Object) {
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "exchange-search-grid-item": UiElements.ExchangeSearchGridItem;
  }
}
