/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   exchange-search-grid-item.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../paper-item/paper-item.d.ts" />
/// <reference path="../star-rating/star-rating.d.ts" />
/// <reference path="exchange-search-item-mixin.d.ts" />

declare namespace UiElements {

  /**
   * `<exchange-search-grid-item>` Displays a single grid item for Exchange
   * search rersults panel.
   *
   * ### Example
   *
   * ```html
   * <exchange-search-grid-item item="{...}" on-download="..."></exchange-search-grid-item>
   * ```
   *
   * ### Styling
   *
   * `<exchange-search-grid-item>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--exchange-search-grid-item` | Mixin applied to the element | `{}`
   * `--exchange-search-grid-item-action-button` | Mixin applied to the visible accrion button | `{}`
   * `--exchange-search-grid-item-card-background-color` | Background color of the card item | `#fff`
   * `--paper-rating-active-color` | Color of the rating icons when highlighted | `--accent-color`
   * `--paper-rating-inactive-color` | Color of the rating icons when not highlighted | `--disabled-text-color`
   * `--exchange-search-grid-item-tags-line` | Mixin applied to the tags container | `{}`
   */
  class ExchangeSearchGridItem extends
    ArcBehaviors.ExchangeSearchItemMixin(
    Object) {
  }
}

interface HTMLElementTagNameMap {
  "exchange-search-grid-item": UiElements.ExchangeSearchGridItem;
}
