/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ExchangeSearchGridItem.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {css, html} from 'lit-element';

import {ExchangeListItemBase} from './ExchangeListItemBase.js';

export {ExchangeSearchGridItem};

declare class ExchangeSearchGridItem extends ExchangeListItemBase {
  constructor();
  render(): any;
}
