/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ExchangeSearchListItem.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {css, html} from 'lit-element';

import {ExchangeListItemBase} from './ExchangeListItemBase.js';

export {ExchangeSearchListItem};

declare namespace UiElements {

  /**
   * `<exchange-search-list-item>` Displays a single list item for Exchange
   * search rersults panel.
   *
   * ### Example
   *
   * ```html
   * <exchange-search-list-item item="{...}" @download="..."></exchange-search-list-item>
   * ```
   */
  class ExchangeSearchListItem extends ExchangeListItemBase {
    constructor();
    render(): any;
  }
}
