/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ExchangeListItemBase.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {ExchangeListItemBase};

declare class ExchangeListItemBase extends LitElement {
  constructor();

  /**
   * Dispatches the `download` custom event to inform the panel
   * about user action.
   */
  requestAction(): void;
  _ratingTemplate(): any;
  _itemIconTemplate(): any;
  _actionButtonTemplate(): any;
}
